### ISSUE TITLE
Registro de metadatos - direccion errónea

### ISSUE THREAD

**Issue by crzyivo** [crzyivo/catmdedit-vv#1]
El repositorio por defecto para la creación de registros de metadatos apunta a una ruta inexistente

**Comment by danieluned** [comment]
<!DOCTYPE html>
<html>
<body>

<h2>Spectacular Mountain</h2>
<img src="pic_mountain.jpg" alt="Mountain View" style="width:304px;height:228px;">

</body>
</html>
