### ISSUE TITLE
Descarga del código fuente del proyecto

### ISSUE THREAD

**Issue by danieluned** [crzyivo/catmdedit-vv#2]
El repositorio por defecto para la creación de registros de metadatos, descrito en el fichero <<catmdedit/repository/sources/metadata.rd>>, apunta a una ruta inexistente (<<E:/workspacesEclipse/.../repository/metadata>>).

**Comment by davidabian** [comment]
@nlucia

**Comment by danieluned** [comment]
/cc @davidabian  @nlucia  @crzyivo  
hola mundo

**Comment by davidabian** [comment]
Este se trata de un defecto antiguo que ya ha sido corregido.
